# Generated by Django 4.2.6 on 2023-11-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_link_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Direccion web"),
        ),
    ]
